from AMSpi import AMSpi

CONVEYOR_MOTOR = AMSpi.DC_Motor_1
PUSHER_MOTOR = AMSpi.DC_Motor_2
DISPENSER_MOTOR = AMSpi.DC_Motor_4

# Setup for voice recognition
SERVER_URL = 'URL_TO_YOUR_SERVER_FOR_VOICE_RECOGNITION'
BUTTON_START_VOICE_RECOGNITION_PIN = 15

# Pin for motion sensor
MOTION_SENSOR_PIN = 17

# Color sensor pins
COLOR_SENSOR_PIN_1 = 2
COLOR_SENSOR_PIN_2 = 3
COLOR_SENSOR_PIN_3 = 23
COLOR_SENSOR_PIN_4 = 24
SIGNAL_SENSOR_PIN = 25

# Pins for shift register
LATCH_REGISTER_PIN = 21
CLK_REGISTER_PIN = 20
SER_REGISTER_PIN = 16

# Pins for motors on Arduino
MOTOR_1_PIN = 5
MOTOR_2_PIN = 6
MOTOR_3_PIN = 13
MOTOR_4_PIN = 19
